### ISSUE TITLE
Would you agree to merge this into cordova-plugin-device?

### ISSUE THREAD

**Issue by pke** [becvert/cordova-plugin-device-name#1]
I have no idea why they removed the `device.name` from the `cordova-plugin-device` but I'd like it to back in there.
Would you be ok to contribute your code to `cordova-plugin-device`?

**Comment by becvert** [comment]
It's been removed from the `cordova-plugin-device` indeed, that's the reason why I did this `cordova-plugin-device-name`. I can't recall why they did that. I'd love to see it back there as well.
Can you ask the [cordova devs](https://issues.apache.org/jira/issues/?jql=project%20%3D%20CB%20AND%20status%20in%20%28Open%2C%20%22In%20Progress%22%2C%20Reopened%29%20AND%20resolution%20%3D%20Unresolved%20AND%20component%20%3D%20%22Plugin%20Device%22%20ORDER%20BY%20priority%20DESC%2C%20summary%20ASC%2C%20updatedDate%20DESC)?

**Comment by becvert** [comment]
[CB-9857](https://issues.apache.org/jira/browse/CB-9857)

**Comment by pke** [comment]
Thats the issue I created, yes. Nobody seemed to care so far. I will ask in the dev list again.

**Comment by pke** [comment]
beside, wouldn't `BluetoothAdapter.getDefaultAdapter();` throw if there is not BT permission set in the manifest?

**Comment by becvert** [comment]
BT permission is in `plugin.xml` and gets added to the manifest on `prepare`

**Comment by pke** [comment]
I'd suggest to just inject the result of this plugin into `device` if its available like this:

```es6
function DeviceName() {
    this.name = null;
    var me = this;
    channel.onCordovaReady.subscribe(function() {
        me.get(function(info) {
            me.name = info.name;
            if (window.device && !windows.device.name) {
              window.device.name = info.name
            }
            channel.onDeviceNameReady.fire();
        }, function(e) {
            utils.alert("[DeviceName] Error initializing Cordova: " + e);
        });
    });
}
```

Pretty smooth and one could then again use `window.device.name` just like before.

**Comment by pke** [comment]
@becvert any thoughts on that?

**Comment by becvert** [comment]
ok.. why not

**Comment by becvert** [comment]
in release 1.2.1
thanks @pke
