### ISSUE TITLE
[Android] device name on 7.0 and above?

### ISSUE THREAD

**Issue by MacGritsch** [becvert/cordova-plugin-device-name#10]
Hi,

is it not possible to get the custom device name from Android devices?
In my case it would be "MacGritschs Phone".

Thank you

**Comment by becvert** [comment]
can you give more details?
how/where did you set your device name "MacGritschs Phone"?
what is the result of `cordova.plugins.deviceName.name` ?
what is your device?
thanks

**Comment by MacGritsch** [comment]
Hi, its a Galaxy Xcover 4 with Android 7.0
I can set the device name under "Settings->About Device->Device Name"
I am new to Android so I can not tell you if that is a new feature of Android 7 or not.

The result of "cordova.plugins.deviceName.name" is still "Galaxy Xcover 4" even after renaming it there.

Thank you and best regards

**Comment by becvert** [comment]
Are you using AndroidStudio?
Could you try 
`Log.d(TAG, "device_name " + Settings.Global.getString(cordova.getActivity().getContentResolver(), "device_name"));`
in the getName method of the file DeviceName.java for instance.
I don't have a Android 7.0 or above to be able to test it myself and I don't want to rely solely on the simulator.
Anyone with such a device can help. Thank you.

**Comment by raxjethvaa** [comment]
its not working with latest android version in 7.0

**Comment by becvert** [comment]
can you try the master branch? thank you.

**Comment by becvert** [comment]
1.3.3 is out. closing now.
