### ISSUE TITLE
[Android] BLUETOOTH permission issue

### ISSUE THREAD

**Issue by zabojad** [becvert/cordova-plugin-device-name#11]
This plugin is add the BLUETOOTH permission in the AndroidManifest.xml.
```
        <config-file target='AndroidManifest.xml' parent='/manifest'>
            <uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="18" />
        </config-file>
```

But when we actually use Bluetooth with the cordova-ble-central-plugin for example, this permission is added twice in the AndroidManifest.xml because of the `android:maxSdkVersion="18"` which leads to the compilation to fail.

Removing `android:maxSdkVersion="18"` solved the issue. Would you like me to issue a PR for that?

**Comment by becvert** [comment]
interesting.
what would you do to solve this?

**Comment by zabojad** [comment]
As I said:
> Removing android:maxSdkVersion="18" solved the issue.

**Comment by becvert** [comment]
I know but there's a reason why maxSdkVersion is there.
Let me think about it...

**Comment by becvert** [comment]
https://issues.apache.org/jira/browse/CB-8401

**Comment by zabojad** [comment]
Good catch. That's exactly the problem we are having.

**Comment by becvert** [comment]
Would you be able to test the master branch please?
I added an [after_prepare hook](https://github.com/becvert/cordova-plugin-device-name/blob/master/merge-bluetooth-permission.js).

**Comment by NikoRoberts** [comment]
So I tried this out. The after_prepare hook worked with a little modification for Cordova 7.x
The Android Manifest file that is produced now is in `platforms/android/app/src/main/AndroidManifest.xml`

The hook I ended up with was
```node
#!/usr/bin/env node

module.exports = function(context) {

    var fs = context.requireCordovaModule('fs');

    var path = context.requireCordovaModule('path');

    var platformRoot = path.join(context.opts.projectRoot, 'platforms/android');

    var preCordova7ManifestFile = path.join(platformRoot, 'AndroidManifest.xml');

    var cordova7ManifestFile = path.join(platformRoot, 'app/src/main/AndroidManifest.xml');

    var manifestEdit = function(file) {
      fs.readFile(file, 'utf8', function (err,data) {
        if (err) {
            throw new Error('Unable to read AndroidManifest.xml: ' + err);
        }
        var permissions = data.match(/<uses-permission(.*?)\/>/g);
        var bluetoothPermissions = permissions.filter(permission => permission.toUpperCase().indexOf('ANDROID.PERMISSION.BLUETOOTH') > -1);
        if (bluetoothPermissions.length > 1) {
            var permissionWithoutMaxSDK = bluetoothPermissions.find(permission => permission.indexOf('android:maxSdkVersion') == -1);
            if (permissionWithoutMaxSDK) {
                var result = data.replace('<uses-permission android:maxSdkVersion="18" android:name="android.permission.BLUETOOTH" />', '');
                fs.writeFile(file, result, 'utf8', function (err) {
                    if (err) {
                        throw new Error('Unable to write into AndroidManifest.xml: ' + err);
                    }
                });
            }
        }
      });
    }

    if (fs.existsSync(preCordova7ManifestFile)) {
      manifestEdit(preCordova7ManifestFile)
    } else if (fs.existsSync(cordova7ManifestFile)) {
      manifestEdit(cordova7ManifestFile)
    }
};

```

**Comment by 573f4n** [comment]
i tried out master branch with NikoRoberts solutions and it works fine. Without the modifiaction of NikoRoberts it doesn't work for Cordova 7.x

**Comment by becvert** [comment]
I updated the master branch.
Can someone test the changes?
If everything's fine I'll do a release.
Thanks

**Comment by 573f4n** [comment]
becvert i tested it and it works fine

**Comment by becvert** [comment]
1.3.3 is out. closing now.
