### ISSUE TITLE
[Android] Bluetooth permission issue fix not working

### ISSUE THREAD

**Issue by aj-dev** [becvert/cordova-plugin-device-name#12]
The fix for the #11 bug doesn't work when there's no space before the self-closing xml element: `<uses-permission android:maxSdkVersion="18" android:name="android.permission.BLUETOOTH"/>`.

Could you update merge-bluetooth-permission.js with the following RegExp to handle both cases?
`var result = data.replace(/<uses-permission android:maxSdkVersion="18" android:name="android\.permission\.BLUETOOTH"\s?\/>/, '');`

**Comment by becvert** [comment]
OK. won't do this before a few days though.

**Comment by aj-dev** [comment]
Any news on this issue?

**Comment by becvert** [comment]
This script fixes what's been introduced by this plugin:
`<uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="18" />`
How do you end up with no space? another plugin?

**Comment by aj-dev** [comment]
Yes, I'm using another plugin https://github.com/don/cordova-plugin-ble-central which inserts `<uses-permission android:name="android.permission.BLUETOOTH"/>` without a space before self closing tag. The plugin has an inconsistent use of spaces vs no spaces. I can create a PR for that plugin if you don't want to update the regex here

**Comment by becvert** [comment]
I'm fine with the RegExp, 
I just want to figure out why you end up with no space.
It does not make sense to me.

**Comment by aj-dev** [comment]
Not sure why but I see that there's no space before all self-closing tags in `platforms/android/app/src/main/AndroidManifest.xml` after running `cordova platform add android`.
<img width="670" alt="screen shot 2018-07-21 at 22 53 39" src="https://user-images.githubusercontent.com/2584733/43040008-8508538c-8d39-11e8-8768-3a520a689f33.png">

**Comment by becvert** [comment]
OK. I'll do an update.

**Comment by becvert** [comment]
done
