### ISSUE TITLE
This plugin gets installed on Windows platforms

### ISSUE THREAD

**Issue by pke** [becvert/cordova-plugin-device-name#3]
and then crashes.
Any way to prevent that?

**Comment by becvert** [comment]
#2 would prevent that I think.
Someone may add support for the windows platform too

**Comment by pke** [comment]
So, merge it then? Thanks ;)
I'll add Windows support later

**Comment by becvert** [comment]
yes I should probably merge this.
but in theory nested js-module are for specialized javascript. which is not the case here.
I feel like js-module ought to be added for specified platforms only.
I'm investigating that issue.

**Comment by pke** [comment]
Na, it solves the problem at hand. That's way better than just crashing the whole Cordova startup on Windows.

**Comment by pke** [comment]
Created #4 with Windows support for you to merge.

**Comment by becvert** [comment]
Thanks. I'll merge it soon.

**Comment by becvert** [comment]
done. please close this issue if everything's fine with you.
