### ISSUE TITLE
[Android] maxSdkVersion below 18 not allowed (1.3.1)

### ISSUE THREAD

**Issue by TMMeijers** [becvert/cordova-plugin-device-name#8]
Since version 1.3.1 which requests bluetooth permissions again and sets the `maxSdkVersion` to 17. The upload to the play store yields the following error message: `The maxSdkVersion of permission android.permission.BLUETOOTH must be at least 18.`

We locked the plugin at 1.3.0 currently which means it won't work for API's below 18 I guess. But that works for now.

**Comment by becvert** [comment]
OK. I'll change the value of maxSdkVersion to 18. Thank you.

**Comment by becvert** [comment]
Please upgrade to 1.3.2

**Comment by TMMeijers** [comment]
Thank you becvert!
